spring:
  config:
    import: classpath:application-mysql.yml, classpath:application-rsa-keys.yml
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: update

logging:
  level:
    org:
      springframework:
        security: debug