
###
POST http://localhost:8080/api/v1/users
Content-Type: application/json

{
  "photo": "https://unsplash.com/8BmNurlVR6M",
  "name": "Víctor Arreaga",
  "about": "Me gusta la idea de intercambiar cosas",
  "numberOfExchanges": 10,
  "rating": 3.6,
  "numberWhatsapp": "0987654321"
}

<> 2023-07-21T145601.500.json

###
POST http://localhost:8080/api/v1/articles
Content-Type: application/json

{
  "userId": "5f3a1d49-d929-483e-82b8-87c5193213fd",
  "title": "Samsung J7 Neo",
  "description": "Este télefono me lo regalaron",
  "images": ["image01", "image02"],
  "category": "ELECTRONICS",
  "state": "PREOWNED",
  "typeArticle": "PUBLISHED",
  "numbersProposals": 20,
  "date": "2023-07-18T17:00:00"
}

<> 2023-07-21T145521.400.json
<> 2023-07-21T122725.500.json
<> 2023-07-21T122059.500.json
<> 2023-07-21T121839.500.json

###
GET http://localhost:8080/api/v1/articles/534291ae-d81c-427c-ace3-44ac2884795f

<> 2023-07-21T125224.400.json

###
GET http://localhost:8080/api/v1/articles/search?title=Samsung J7 Neo&category=ELECTRONICS&state=PREOWNED

<> 2023-07-21T133313.200.json
<> 2023-07-21T133239.200.json

###
PUT http://localhost:8080/api/v1/articles/008e2482-b7e2-4974-a480-39ae78abe66a
Content-Type: application/json

{
  "userId": "5f3a1d49-d929-483e-82b8-87c5193213fd",
  "title": "Samsung J7 Neo",
  "description": "Este télefono me lo regalaron, pero no lo uso porque tengo otro mejor y quiero intercambiarlo por un celular de gama media",
  "images": ["image01", "image02"],
  "category": "ELECTRONICS",
  "state": "PREOWNED",
  "typeArticle": "PUBLISHED",
  "numbersProposals": 2,
  "date": "2023-07-18T17:00:00"
}

###
GET http://localhost:8080/api/v1/articles/search?title=Samsung J7 Neo&category=ELECTRONICS&state=PREOWNED