INSERT INTO users (username, name, about, photo, password, number_whatsapp)
VALUES
    ('varreagae','Víctor Arreaga','Desarrollador de Software con componentes de computadoras que me gustaría intercambiar.','https://is.gd/52avWg','varreagae','0939076291'),
    ('jzuritav','Jacinto Zurita','Soy estudiante universitario. Me gusta leer y salir con amigos.','https://is.gd/yfSyyC','jzuritav','0978523906'),
    ('pedro01','Pedro Fernandez','Trabajo en una empresa de tecnología. Me gusta hacer deportes.','https://randomuser.me/api/portraits/men/12.jpg','zxc098asd','0962937584'),
    ('laura_gomez','Laura Gomez','Soy mamá de dos niños. Me gusta cocinar y pasar tiempo con mi familia.','https://randomuser.me/api/portraits/women/36.jpg','abc12345','0928473829'),
    ('john32','Juan Perez','Trabajo en una empresa de desarrollo de software. Me gusta el cine.','https://randomuser.me/api/portraits/men/48.jpg','123456qw','0955555595'),
    ('sofia_05','Sofia Rodriguez','Soy estudiante de ingeniería. Me gustan los videojuegos y salir con amigos.','https://randomuser.me/api/portraits/women/12.jpg','abc123qwe','0977712356'),
    ('felipe25','Felipe Torres','Trabajo en una empresa de retail. Me gusta el fútbol y la música.','https://randomuser.me/api/portraits/men/24.jpg','123qweasd','0922233304'),
    ('clara_r','Clara Rodriguez','Soy profesora de literatura. Me gusta leer y escribir.','https://randomuser.me/api/portraits/women/48.jpg','abc123456','0944555123'),
    ('sebastian79','Sebastian Lopez','Trabajo en ventas. Me gusta viajar y conocer nuevos lugares.','https://randomuser.me/api/portraits/men/36.jpg','abc123def','0933344499'),
    ('lucia_g','Lucia Gonzalez','Soy diseñadora gráfica freelance. Me gusta dibujar y pintar.','https://randomuser.me/api/portraits/women/12.jpg','zxc098asd','0999111226'),
    ('mariagarcia','Maria Garcia','Me dedico a la docencia en una escuela primaria.','https://randomuser.me/api/portraits/women/68.jpg','asdasd123','0995938762'),
    ('juanlopez','Juan Lopez','Soy arquitecto y me gusta el diseño de interiores.','https://randomuser.me/api/portraits/men/43.jpg','1234qwer','0998337625'),
    ('anamartinez','Ana Martinez','Trabajo en una empresa de marketing digital.','https://randomuser.me/api/portraits/women/24.jpg','zxcvb123','0997765543'),
    ('kevin79','Kevin Torres','Soy estudiante de nutrición deportiva y me gusta el gym.','https://randomuser.me/api/portraits/men/42.jpg','123456789','0996142738'),
    ('jimena','Jimena García','Me dedico al cuidado de adultos mayores.','https://randomuser.me/api/portraits/women/12.jpg','abcd1234','0995432156'),
    ('diegosanchez','Diego Sanchez','Trabajo como vendedor en una tienda de electrónicos.','https://randomuser.me/api/portraits/men/24.jpg','qwerty123','0990021456'),
    ('ximena27','Ximena Herrera','Soy profesora de yoga y pilates.','https://randomuser.me/api/portraits/women/68.jpg','asd12345','0996132365'),
    ('sebastian01','Sebastian Ruiz','Estoy estudiando programación web.','https://randomuser.me/api/portraits/men/35.jpg','sebas123','0990998877'),
    ('claudia13','Claudia Martinez','Me dedico a la edición de videos y contenido audiovisual.','https://randomuser.me/api/portraits/women/29.jpg','video123','0992256985'),
    ('mauro','Mauro Fernandez','Trabajo en una empresa financiera.','https://randomuser.me/api/portraits/men/32.jpg','finance1','0998753241'),
    ('paula56','Paula Lopez','Soy profesora de literatura en la universidad.','https://randomuser.me/api/portraits/women/68.jpg','libros123','0990044991'),
    ('maximiliano','Maximiliano Garcia','Soy médico especialista en cardiología.','https://randomuser.me/api/portraits/men/43.jpg','doctormax','0996223377'),
    ('emiliano34','Emiliano Torres','Me gusta hacer videos para Youtube.','https://randomuser.me/api/portraits/men/18.jpg','ytvideos','0997665544'),
    ('florencia79','Florencia Suarez','Trabajo desde mi casa como diseñadora independiente.','https://randomuser.me/api/portraits/women/34.jpg','flosuarez','0991236547'),
    ('gabriel','Gabriel Rodriguez','Soy ingeniero en sistemas.','https://randomuser.me/api/portraits/men/24.jpg','ingeniero123','0995432187'),
    ('eliana','Eliana Perez','Me dedico al cuidado de niños como niñera.','https://randomuser.me/api/portraits/women/23.jpg','elianap','0997654312'),
    ('federicog','Federico Garcia','Estudio marketing y trabajo en una agencia publicitaria.','https://randomuser.me/api/portraits/men/12.jpg','federicog1','0991122334'),
    ('raquel','Raquel Gimenez','Soy profesora de preescolar en un jardín.','https://randomuser.me/api/portraits/women/21.jpg','preescolar1','0995647382'),
    ('juanm','Juan Martinez','Trabajo como programador web freelance.','https://randomuser.me/api/portraits/men/42.jpg','juanm123','0990876543'),
    ('yamila','Yamila Fernandez','Estoy estudiando para ser veterinaria.','https://randomuser.me/api/portraits/women/34.jpg','yamfer','0996654321');
