###
POST http://localhost:8080/api/v1/articles
Content-Type: application/json

{
  "userId": "06fcffc5-523f-4ede-8416-afa86fd067c8",
  "title": "Mouse marvo",
  "description": "No funciona el botón derecho",
  "images": ["https://is.gd/J7tWNO"],
  "category": "Electrónica",
  "state": "Baja calidad",
  "typeArticle": "Publicado",
  "numbersProposals": 1,
  "date": "2023-08-23T20:10:10"
}
###
GET http://localhost:8080/api/v1/articles

###
GET http://localhost:8080/api/v1/articles/search?title=&category=Electrónica&state=Nuevo

###
PUT http://localhost:8080/api/v1/articles/f5256ad2-0f29-48e9-a5fe-8b651f8a34c5
Content-Type: application/json

{
  "id": "f5256ad2-0f29-48e9-a5fe-8b651f8a34c5",
  "userId": "06fcffc5-523f-4ede-8416-afa86fd067c8",
  "title": "MacBook Pro 2019",
  "description": "No tiene mucho uso, prácticamente nuevo",
  "images": ["https://is.gd/J7tWNO", "image02", "image03"],
  "category": "Electrónica",
  "state": "Usado",
  "typeArticle": "Publicado",
  "numbersProposals": 15,
  "date": "2023-07-22T20:10:10"
}

###
DELETE http://localhost:8080/api/v1/articles/1065900-84f4-4d1e-946a-39d57e0e9675