###
POST http://localhost:8080/api/v1/articles/862093c6-6f3f-4dac-8e7a-bc9c7add99eb
Content-Type: application/json

{
  "title": "Laptop HP",
  "description": "No funciona el botón derecho",
  "images": ["https://is.gd/J7tWNO"],
  "category": "ELECTRONICS",
  "state": "NEW"
}

###
PUT http://localhost:8080/api/v1/articles/e088003c-70df-4ad2-8f81-68e844fc7052
Content-Type: application/json

{
  "title": "Nuevo",
  "description": "No funciona el botón derecho",
  "images": ["https://is.gd/J7tWNO", "https://is.gd/x7tWNO"],
  "category": "ELECTRONICS",
  "state": "PREOWNED"
}

###
POST http://localhost:8080/api/v1/articles
Content-Type: application/json

{
  "userId": "9100a01a-a61e-4f41-85cc-7f21443329ab",
  "title": "Macbook pro 2019",
  "description": "No tiene mucho uso, prácticamente nuevo",
  "images": ["https://is.gd/g95AEt", "https://is.gd/ogtAoe"],
  "category": "Electrónica"
}


###
POST http://localhost:8080/api/v1/articles
Content-Type: application/json

{
  "userId": "32e7bf44-b44e-480f-8c45-42592d2e188d",
  "title": "Biblia RVR1960",
  "description": "No tiene mucho uso, prácticamente nuevo",
  "images": ["https://is.gd/DdAob3"],
  "category": "Libros texto material educativo",
  "state": "Usado"
}
###
GET http://localhost:8080/api/v1/articles

###
GET http://localhost:8080/api/v1/articles/search?title=&category=Electrónica&state=Nuevo

###
PUT http://localhost:8080/api/v1/articles/1cdbcf41-7abb-4f83-b67e-0f1370dae991
Content-Type: application/json

{
  "id": "1cdbcf41-7abb-4f83-b67e-0f1370dae991",
  "userId": "02e34170-70e6-4100-ac8a-c871e299cbb2",
  "title": "Mouse marvo",
  "description": "No funciona el botón derecho",
  "images": ["https://is.gd/J7tWNO"],
  "category": "Electrónica",
  "state": "Seminuevo",
  "articleType": "Publicado",
  "numbersProposals": 2,
  "date": "2023-08-23T20:10:10"
}

###
DELETE http://localhost:8080/api/v1/articles/e088003c-70df-4ad2-8f81-68e844fc7052

###
GET http://localhost:8080/api/v1/articles/5695978c-213f-410b-8f98-e1793ed8c613