###
POST http://localhost:8080/api/v1/users
Content-Type: application/json

{
  "photo": "https://github.com/vfred0.png",
  "username": "vfred0",
  "name": "Víctor Arreaga",
  "about": "Me gusta la idea de intercambiar cosas, porque así puedo obtener cosas que necesito sin gastar dinero",
  "numberWhatsapp": "0912345671",
  "password": "12345"
}

###
POST http://localhost:8080/api/v1/users
Content-Type: application/json

{
  "photo": "https://is.gd/G5qCMW",
  "username": "rrocham",
  "name": "Roxana Rocha",
  "about": "Tenemos varios libros que ya no usamos, pero nos gustaría intercambiarlos por otros que no hemos leído",
  "numberWhatsapp": "0912345672",
  "password": "12345"
}

###
POST http://localhost:8080/api/v1/users
Content-Type: application/json

{
  "photo": "https://is.gd/52avWg",
  "username": "varreagae",
  "name": "Víctor Arreaga",
  "about": "Me gustaría intermcabiar los artículos que no uso.",
  "numberWhatsapp": "0912345679",
  "password": "victor"
}

###
PUT http://localhost:8080/api/v1/users/83cdae70-d0e1-4385-bc99-b44dbb9d6a84
Content-Type: application/json

{
  "id": "83cdae70-d0e1-4385-bc99-b44dbb9d6a84",
  "username": "xx1",
  "photo": "https://is.gd/YY9Rd8",
  "name": "Actualizado",
  "about": "Tnego varios libros que ya no uso, pero me gustaría intercambiarlos por otros que no he leído",
  "numberWhatsapp": "09x9345678",
  "password": "12345"
}


###
POST http://localhost:8080/api/v1/users
Content-Type: application/json

{
  "photo": "https://is.gd/YY9Rd8",
  "username": "vfred0",
  "name": "Víctor Arreaga",
  "about": "Me gusta la idea de intercambiar cosas, porque así puedo obtener cosas que necesito sin gastar dinero",
  "numberOfExchanges": 10,
  "rating": 5,
  "numberWhatsapp": "0987654321",
  "password": "victor"
}

###
PUT http://localhost:8080/api/v1/users/33ff0b32-51a2-4801-9457-8650f4aa2171
Content-Type: application/json

{
  "id": "33ff0b32-51a2-4801-9457-8650f4aa2171",
  "photo": "https://is.gd/YY9Rd8",
  "username": "vfred0",
  "name": "Víctor Arreaga",
  "about": "Me gusta la idea de intercambiar cosas, porque así puedo obtener cosas que necesito sin gastar dinero",
  "numberOfExchanges": 10,
  "rating": 5,
  "numberWhatsapp": "0987654321",
  "password": "victor"
}

###
GET http://localhost:8080/api/v1/users

###
DELETE http://localhost:8080/api/v1/users/83cdae70-d0e1-4385-bc99-b44dbb9d6a84
