###
POST http://localhost:8080/api/v1/users
Content-Type: application/json

{
  "photo": "https://is.gd/Xp9Pwj",
  "username": "rrocham",
  "name": "Roxana Rocha",
  "about": "Tnego varios libros que ya no uso, pero me gustaría intercambiarlos por otros que no he leído",
  "numberWhatsapp": "0912345678",
  "password": "12345"
}

###
POST http://localhost:8080/api/v1/users
Content-Type: application/json

{
  "photo": "https://is.gd/52avWg",
  "username": "varreagae",
  "name": "Víctor Arreaga",
  "about": "Me gustaría intermcabiar los artículos que no uso.",
  "numberWhatsapp": "0912345679",
  "password": "victor"
}

###
PUT http://localhost:8080/api/v1/users/d6fbf2c9-9e71-4c3b-b973-2b6324486a4b
Content-Type: application/json

{
  "id": "d6fbf2c9-9e71-4c3b-b973-2b6324486a4b",
  "username": "rrocham",
  "photo": "https://is.gd/YY9Rd8",
  "name": "Roxana Rocha",
  "about": "Tnego varios libros que ya no uso, pero me gustaría intercambiarlos por otros que no he leído",
  "numberWhatsapp": "0912345678",
  "password": "12345"
}


###
POST http://localhost:8080/api/v1/users
Content-Type: application/json

{
  "photo": "https://is.gd/YY9Rd8",
  "username": "vfred0",
  "name": "Víctor Arreaga",
  "about": "Me gusta la idea de intercambiar cosas, porque así puedo obtener cosas que necesito sin gastar dinero",
  "numberOfExchanges": 10,
  "rating": 5,
  "numberWhatsapp": "0987654321",
  "password": "victor"
}

###
PUT http://localhost:8080/api/v1/users/33ff0b32-51a2-4801-9457-8650f4aa2171
Content-Type: application/json

{
  "id": "33ff0b32-51a2-4801-9457-8650f4aa2171",
  "photo": "https://is.gd/YY9Rd8",
  "username": "vfred0",
  "name": "Víctor Arreaga",
  "about": "Me gusta la idea de intercambiar cosas, porque así puedo obtener cosas que necesito sin gastar dinero",
  "numberOfExchanges": 10,
  "rating": 5,
  "numberWhatsapp": "0987654321",
  "password": "victor"
}

###
GET http://localhost:8080/api/v1/users

