package ec.edu.unemi.unimart.utils;

public enum Category {
    TEXT_BOOKS_EDUCATIONAL_MATERIAL,
    OFFICE_SUPPLIES,
    ELECTRONICS,
    FURNITURE_AND_DECORATION,
    CLOTHING,
    LABORATORY_MATERIAL,
    MUSICAL_INSTRUMENTS,
    SPORTING_GOODS,
    ARTS_HANDICRAFTS,
    TOYS_GAMES
}
